### PR TITLE
Add trusted types support

### PR DESCRIPTION
**Pull request by rictic**
Makes the Karma jasmine html reporter compatible with an enforced Trusted Types policy.

This should only be necessary for a limited time, as the next version of the proposed specification will not require any special code for URLS (except javascript: URLS).

More info about the proposed Trusted Types standard at https://github.com/WICG/trusted-types

### CODE REVIEW

**Comment by rictic** [comment]
Related: https://github.com/karma-runner/karma/pull/3360

**Comment by dfederm** [comment]
See: https://github.com/dfederm/karma-jasmine-html-reporter/blob/master/README.md#develop

Basically, make the change to Jasmine and then I'll copy it into this package

**Comment by rictic** [comment]
Sent over https://github.com/jasmine/jasmine/pull/1750

**Comment by engelsdamien** [comment]
What is the status of this change ?

**Comment by rictic** [comment]
On revisiting, I don't think this is necessary anymore, as the shipping version of TrustedTypes doesn't have or need the createURL function.

**Pull request closed without merging**
